# Generated by Django 4.1.1 on 2022-11-21 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MEMBERS',
            fields=[
                ('m_id', models.CharField(db_column='M_ID', max_length=250, primary_key=True, serialize=False)),
                ('m_password', models.CharField(db_column='M_PASSWORD', max_length=250)),
                ('m_name', models.CharField(db_column='M_NAME', max_length=250)),
            ],
        ),
    ]
