# Generated by Django 4.1.1 on 2022-11-21 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DRUGINFO',
            fields=[
                ('d_drugname', models.CharField(db_column='d_drugname', max_length=250, primary_key=True, serialize=False)),
                ('d_effect', models.CharField(db_column='d_effect', max_length=250)),
                ('d_usage', models.CharField(db_column='d_usage', max_length=250)),
                ('d_volume', models.CharField(db_column='d_volume', max_length=250)),
                ('d_info', models.CharField(db_column=' d_info', max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Search_History',
            fields=[
                ('h_id', models.OneToOneField(db_column='H_ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='accounts.members')),
                ('h_date', models.DateField(db_column='H_DATE')),
                ('h_druginfo', models.ForeignKey(db_column='H_DRUGINFO', on_delete=django.db.models.deletion.DO_NOTHING, to='list.druginfo', to_field='d_info')),
            ],
        ),
    ]
