# Generated by Django 4.1.1 on 2022-11-23 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("list", "0003_search_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="search",
            name="img",
            field=models.ImageField(blank=True, null=True, upload_to="search/media"),
        ),
    ]
