# Generated by Django 4.1.1 on 2022-11-23 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("list", "0004_search_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="search",
            name="mediDream_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="accounts.members",
            ),
        ),
        migrations.AlterField(
            model_name="search",
            name="pill",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="list.pillinfo",
            ),
        ),
    ]
