# Generated by Django 4.1.1 on 2022-11-23 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("list", "0005_alter_search_medidream_id_alter_search_pill"),
    ]

    operations = [
        migrations.AlterField(
            model_name="search",
            name="img",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
