# Generated by Django 4.1.1 on 2022-11-30 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0007_alter_search_medidream_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pillinfo',
            name='box_picture',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='pillinfo',
            name='pill_picture',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='pillinfo',
            name='pill_caution',
            field=models.CharField(max_length=500),
        ),
    ]
