# Generated by Django 4.1.1 on 2022-11-30 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0008_pillinfo_box_picture_pillinfo_pill_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pillinfo',
            name='pill_caution',
            field=models.CharField(max_length=3000),
        ),
    ]
