# Generated by Django 4.1.1 on 2022-11-30 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0009_alter_pillinfo_pill_caution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pillinfo',
            name='pill_caution',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='pillinfo',
            name='pill_usage',
            field=models.CharField(max_length=5000),
        ),
    ]
