# Generated by Django 4.1.1 on 2022-11-30 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0010_alter_pillinfo_pill_caution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pillinfo',
            name='medication_information',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='pillinfo',
            name='pill_caution',
            field=models.CharField(max_length=50000),
        ),
    ]
