# Generated by Django 4.1.1 on 2022-11-30 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0014_alter_pillinfo_medication_information_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pillinfo',
            name='pill_ingredient',
            field=models.TextField(max_length=5000, null=True),
        ),
    ]
