# Generated by Django 4.1.1 on 2022-11-30 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0016_alter_pillinfo_pill_effect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pillinfo',
            name='pill_effect',
            field=models.TextField(max_length=1000),
        ),
    ]
